Repository breezy-weather/breezy-weather, pull requests merged in 2024-12, with the labels that each got.

#1476 Miscellaneous geo-related fixes
  app/src/main/java/org/breezyweather/common/source/LocationPreset.kt
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-zh-rHK/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
  app/src/src_nonfreenet/org/breezyweather/sources/dmi/DmiService.kt
  app/src/src_nonfreenet/org/breezyweather/sources/metno/MetNoService.kt
  app/src/src_nonfreenet/org/breezyweather/sources/metoffice/MetOfficeService.kt
  app/src/src_nonfreenet/org/breezyweather/sources/nws/NwsService.kt
  app/src/src_nonfreenet/org/breezyweather/sources/smg/SmgResultConverter.kt
Labels: Needs rebase

#1483 added LVGMC as a new source
  app/src/main/java/org/breezyweather/common/source/LocationPreset.kt
  app/src/src_nonfreenet/org/breezyweather/sources/SourceManager.kt
  app/src/src_nonfreenet/org/breezyweather/sources/lvgmc/LvgmcApi.kt
  app/src/src_nonfreenet/org/breezyweather/sources/lvgmc/LvgmcResultConverter.kt
  app/src/src_nonfreenet/org/breezyweather/sources/lvgmc/LvgmcService.kt
  app/src/src_nonfreenet/org/breezyweather/sources/lvgmc/json/LvgmcAirQualityLocationResult.kt
  app/src/src_nonfreenet/org/breezyweather/sources/lvgmc/json/LvgmcAirQualityResult.kt
  app/src/src_nonfreenet/org/breezyweather/sources/lvgmc/json/LvgmcCurrentLocation.kt
  app/src/src_nonfreenet/org/breezyweather/sources/lvgmc/json/LvgmcCurrentResult.kt
  app/src/src_nonfreenet/org/breezyweather/sources/lvgmc/json/LvgmcForecastResult.kt
Labels: Needs review

#1486 Fix #1474 - Handle multiple refresh errors
  app/src/main/java/org/breezyweather/common/extensions/ModifierExtensions.kt
  app/src/main/java/org/breezyweather/main/MainActivity.kt
  app/src/main/java/org/breezyweather/main/MainActivityViewModel.kt
  app/src/main/res/layout-w640dp/activity_main.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: Needs review

#1493 added ClimWeb for 17 African countries
  app/src/main/java/org/breezyweather/common/source/LocationPreset.kt
  app/src/main/java/org/breezyweather/sources/climweb/AnamBfService.kt
  app/src/main/java/org/breezyweather/sources/climweb/AnametService.kt
  app/src/main/java/org/breezyweather/sources/climweb/ClimWebApi.kt
  app/src/main/java/org/breezyweather/sources/climweb/ClimWebResultConverter.kt
  app/src/main/java/org/breezyweather/sources/climweb/ClimWebService.kt
  app/src/main/java/org/breezyweather/sources/climweb/DccmsService.kt
  app/src/main/java/org/breezyweather/sources/climweb/DmnNeService.kt
  app/src/main/java/org/breezyweather/sources/climweb/DwrGmService.kt
  app/src/main/java/org/breezyweather/sources/climweb/EthioMetService.kt
  app/src/main/java/org/breezyweather/sources/climweb/GMetService.kt
  app/src/main/java/org/breezyweather/sources/climweb/IgebuService.kt
  app/src/main/java/org/breezyweather/sources/climweb/InmgbService.kt
  app/src/main/java/org/breezyweather/sources/climweb/MaliMeteoService.kt
  app/src/main/java/org/breezyweather/sources/climweb/MeteoBeninService.kt
  app/src/main/java/org/breezyweather/sources/climweb/MeteoTchadService.kt
  app/src/main/java/org/breezyweather/sources/climweb/MettelsatService.kt
  app/src/main/java/org/breezyweather/sources/climweb/MsdZwService.kt
  app/src/main/java/org/breezyweather/sources/climweb/SmaScService.kt
  app/src/main/java/org/breezyweather/sources/climweb/SmaSuService.kt
  app/src/main/java/org/breezyweather/sources/climweb/SsmsService.kt
  app/src/main/java/org/breezyweather/sources/climweb/json/ClimWebAlertsResult.kt
  app/src/main/java/org/breezyweather/sources/climweb/json/ClimWebLocation.kt
  app/src/main/java/org/breezyweather/sources/climweb/json/ClimWebNormals.kt
  app/src/main/java/org/breezyweather/sources/climweb/serializers/ClimWebAnySerializer.kt
  app/src/main/res/values/strings.xml
  app/src/src_nonfreenet/org/breezyweather/sources/SourceManager.kt
Labels: Needs review

#1506 Improve UI of refresh error details dialog
  app/src/main/java/org/breezyweather/main/MainActivity.kt
Labels: Needs review

#1505 Replace deprecated getParcelable methods
  app/src/main/java/org/breezyweather/main/MainActivity.kt
  app/src/main/java/org/breezyweather/remoteviews/common/WidgetSizeUtils.kt
Labels: Needs review

#1561 added Ilmateenistus and EKUK as new sources
  app/src/main/java/org/breezyweather/common/source/LocationPreset.kt
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
  app/src/src_nonfreenet/org/breezyweather/sources/SourceManager.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ekuk/EkukApi.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ekuk/EkukResultConverter.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ekuk/EkukService.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ekuk/json/EkukObservationsResult.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ekuk/json/EkukStation.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ekuk/json/EkukStationGeometry.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ekuk/json/EkukStationProperties.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ekuk/json/EkukStationsResult.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ilmateenistus/IlmateenistusApi.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ilmateenistus/IlmateenistusResultConverter.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ilmateenistus/IlmateenistusService.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ilmateenistus/json/IlmateenistusForecast.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ilmateenistus/json/IlmateenistusForecastAttributes.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ilmateenistus/json/IlmateenistusForecastItem.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ilmateenistus/json/IlmateenistusForecastResult.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ilmateenistus/json/IlmateenistusForecastTabular.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ilmateenistus/json/IlmateenistusForecastTime.kt
  app/src/src_nonfreenet/org/breezyweather/sources/nws/NwsResultConverter.kt
  docs/COVERAGE.md
  docs/SOURCES.md
Labels: New source
