Repository breezy-weather/breezy-weather, pull requests merged in 2025-07, with the labels that each got.

#1955 Fix #1925 - fixed Sun/Moon charts
  app/src/main/java/org/breezyweather/ui/common/charts/EphemerisChart.kt
  app/src/main/java/org/breezyweather/ui/details/DetailsScreen.kt
  app/src/main/java/org/breezyweather/ui/details/components/DetailsSunMoon.kt
Labels: Bug

#1361 Modified getCurrentUVFromDayMax with a more attenuated model
  app/src/main/java/org/breezyweather/sources/CommonConverter.kt
Labels: Needs review

#1981 Fix #1977 - NCEI
  app/src/main/java/org/breezyweather/common/source/LocationPreset.kt
  app/src/src_nonfreenet/org/breezyweather/sources/SourceManager.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ncei/NceiApi.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ncei/NceiResultConverter.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ncei/NceiService.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ncei/json/NceiDataResult.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ncei/json/NceiStationsCentroid.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ncei/json/NceiStationsResult.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ncei/json/NceiStationsResultResults.kt
  app/src/src_nonfreenet/org/breezyweather/sources/ncei/json/NceiStationsResultResultsStation.kt
Labels: Needs more info

#2019 WIP improve accessibility of daily/hourly trends
  CHANGELOG.md
  app/src/main/java/org/breezyweather/common/extensions/DisplayExtensions.kt
  app/src/main/java/org/breezyweather/ui/common/widgets/trend/TrendRecyclerView.kt
  app/src/main/java/org/breezyweather/ui/common/widgets/trend/chart/DoubleHistogramView.kt
  app/src/main/java/org/breezyweather/ui/common/widgets/trend/chart/PolylineAndHistogramView.kt
  app/src/main/java/org/breezyweather/ui/common/widgets/trend/item/DailyTrendItemView.kt
  app/src/main/java/org/breezyweather/ui/common/widgets/trend/item/HourlyTrendItemView.kt
  app/src/main/java/org/breezyweather/ui/main/adapters/main/holder/DailyViewHolder.kt
  app/src/main/java/org/breezyweather/ui/main/adapters/main/holder/HourlyViewHolder.kt
  app/src/main/java/org/breezyweather/ui/main/layouts/TrendHorizontalLinearLayoutManager.kt
  app/src/main/res/layout/item_trend_daily.xml
  app/src/main/res/layout/item_trend_hourly.xml
  app/src/main/res/values/dimens.xml
  docs/HOMEPAGE.md
Labels: Priority: high, Accessibility
